export const GET_CONTACTS_LOADING = "GET_CONTACTS_LOADING";
export const GET_CONTACTS_ERROR = "GET_CONTACTS_ERROR";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";

export const POST_CONTACT_LOADING = "POST_CONTACTS_LOADING";
export const POST_CONTACT_ERROR = "POST_CONTACT_ERROR";
export const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS";

export const PATCH_CONTACT_LOADING = "PATCH_CONTACTS_LOADING";
export const PATCH_CONTACT_ERROR = "PATCH_CONTACT_ERROR";
export const PATCH_CONTACT_SUCCESS = "PATCH_CONTACT_SUCCESS";

export const DELETE_CONTACT_LOADING = 'DELETE_CONTACTS_LOADING';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
