export const SELECT_CONTACT = "SELECT_CONTACT";

export const POST_SLOT_LOADING = "POST_SLOTS_LOADING";
export const POST_SLOT_ERROR = "POST_SLOT_ERROR";
export const POST_SLOT_SUCCESS = "POST_SLOT_SUCCESS"

export const GET_SLOT_LOADING = "GET_SLOTS_LOADING";
export const GET_SLOT_ERROR = "GET_SLOT_ERROR";
export const GET_SLOT_SUCCESS = "GET_SLOT_SUCCESS"